### ISSUE TITLE
net/http doesn't like our cert

### ISSUE THREAD

**Issue by Q-Mart** [UniversityRadioYork/myradio-go#1]
Trying to test this out and I'm getting 'Get https://ury.org.uk/api/v2/list/alllists?api_key=INSERT_KEY_HERE x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO RSA Certification Authority")' from net/http.Client.

[This link] (https://groups.google.com/forum/#!topic/golang-nuts/v5ShM8R7Tdc) tells me that go doesn't trust our SSL cert from some reason however I am yet to pinpoint it

**Comment by adfw** [comment]
It probably needs pointing to the root CA store. No idea how you do that in go. Also, you managed to email your dev key to everyone on the subscription list. I *strongly* recommend regenerating it for security reasons.

**Comment by Q-Mart** [comment]
Thanks to @LordAro, this problem was resolved by upgrading to go 1.5

Also I am very silly
