### ISSUE TITLE
GetSearchMeta doesn't escape full stops in the query

### ISSUE THREAD

**Issue by markspolakovs** [UniversityRadioYork/myradio-go#67]
Special characters in a search will get dumped into the URL directly, e.g. `/show/searchmeta/.mov`.

Bit of an L

**Comment by alyxbb** [comment]
.'s dont need encoding, the issue is the nginx config blocking paths containing `/.` to prevent accessing hidden files. see  [UniversityRadioYork/MyRadio#1200](https://github.com/UniversityRadioYork/MyRadio/issues/1200)
